### ISSUE TITLE
Patch is related to SMG and not to Earth Seeker

### ISSUE THREAD

**Issue by manuelx98** [viktormax3/Earth-Seeker-Riiv-to-WBFS#1]
Apparently the patch is the same one used for SMG-Riiv-to-WBFS, and it fails to find my Earth Seeker WBFS NTSC-J, asking for a SMG one instead.

![Screenshot (124)](https://user-images.githubusercontent.com/18691849/72656594-a5f1f380-399c-11ea-8e92-8ed830d67cef.png)

**Comment by viktormax3** [comment]
I haven't uploaded the script yet, I'm waiting for a new update of the game translation
